# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Moody' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for Moody
    use_frameworks!
    pod 'AWSMobileClient', '~> 2.6.13'
    pod 'AWSCore', '~> 2.10.0'
     # other pods
   end

  target 'MoodyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoodyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

